### ISSUE TITLE
是否考虑增加一个懒加载Preload的方案？

### ISSUE THREAD

**Issue by hinego** [swiftcarrot/queryx#16]
例如
```
type User struct {
	Info *Info
}

func (r *User) GetInfo() *Info {
	if r.Info == nil {
		// 执行查询
		//r.Info = xxxx
	}
	return r.Info
}

type Info struct{}
```

这样就不提前写Preload。需要时再查询！也能提高一下性能（某些时候可能预加载了，但是未必会用）

**Comment by hinego** [comment]
要不要建个群吧 一起交流一下？telegram/wechat都行

**Comment by hinego** [comment]
另外 进行条件判断是 EQ 改为Eq 这样是不是好看一点....

我现在用的自己魔改的gorm gen

**Comment by wangzuo** [comment]
我觉得可以在model上多生成一个preload方法来满足这个需求，比如:

```go
user, err := c.QueryUser().Find(1)
user.PreloadInfo()
fmt.Println(user.Info)
```

这个方法实现和你的类似

```go
func (u *User) PreloadInfo() error {
  if (u.Info == nil) {
    info, err = u.queries.QueryInfo()...
    if err != nil {
      return err
    }
    u.Info = info
  }
  return nil
}
```

> 另外 进行条件判断是 EQ 改为Eq 这样是不是好看一点....

按照 go 的命名习惯缩写应该都是大写吧?

> 要不要建个群吧 一起交流一下？telegram/wechat都行

已建微信群，欢迎

![image](https://github.com/swiftcarrot/queryx/assets/1039026/e956ebc8-1b31-4e33-b6f0-5e45278e25bf)

**Comment by wangzuo** [comment]
移动到 #18 讨论
